<a href="https://colab.research.google.com/github/NatashaKamami/Python-Data-Analysis/blob/main/Deleting_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Iris

### Introduction:

This exercise may seem a little bit strange, but keep doing it.

### Step 1. Import the necessary libraries

In [ ]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data).

### Step 3. Assign it to a variable called iris

In [ ]:
iris = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')

### Step 4. Create columns for the dataset

In [ ]:
# 1. sepal_length (in cm)
# 2. sepal_width (in cm)
# 3. petal_length (in cm)
# 4. petal_width (in cm)
# 5. class
iris.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']

### Step 5.  Is there any missing value in the dataframe?

In [ ]:
iris.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
class           0
dtype: int64

### Step 6.  Lets set the values of the rows 10 to 29 of the column 'petal_length' to NaN

In [ ]:
iris.loc[10:29, 'petal_length'] = np.nan
iris.loc[10:29, 'petal_length']

10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
20   NaN
21   NaN
22   NaN
23   NaN
24   NaN
25   NaN
26   NaN
27   NaN
28   NaN
29   NaN
Name: petal_length, dtype: float64

### Step 7. Good, now lets substitute the NaN values to 1.0

In [ ]:
iris['petal_length'].fillna(1.0, inplace=True)
iris.loc[10:29, 'petal_length']

<ipython-input-8-ced6e86ee864>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  iris['petal_length'].fillna(1.0, inplace=True)

10    1.0
11    1.0
12    1.0
13    1.0
14    1.0
15    1.0
16    1.0
17    1.0
18    1.0
19    1.0
20    1.0
21    1.0
22    1.0
23    1.0
24    1.0
25    1.0
26    1.0
27    1.0
28    1.0
29    1.0
Name: petal_length, dtype: float64

### Step 8. Now let's delete the column class

In [ ]:
iris.drop(columns=['class'], inplace=True)
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')

### Step 9.  Set the first 3 rows as NaN

In [ ]:
iris.iloc[:3] = np.nan
iris.iloc[:3]

   sepal_length  sepal_width  petal_length  petal_width
0           NaN          NaN           NaN          NaN
1           NaN          NaN           NaN          NaN
2           NaN          NaN           NaN          NaN

### Step 10.  Delete the rows that have NaN

In [ ]:
iris.dropna(inplace=True)
iris.head()

   sepal_length  sepal_width  petal_length  petal_width
3           5.0          3.6           1.4          0.2
4           5.4          3.9           1.7          0.4
5           4.6          3.4           1.4          0.3
6           5.0          3.4           1.5          0.2
7           4.4          2.9           1.4          0.2

### Step 11. Reset the index so it begins with 0 again

In [ ]:
iris.reset_index(drop=True, inplace=True)
iris.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.0          3.6           1.4          0.2
1           5.4          3.9           1.7          0.4
2           4.6          3.4           1.4          0.3
3           5.0          3.4           1.5          0.2
4           4.4          2.9           1.4          0.2

### BONUS: Create your own question and answer it.

In [ ]:
# Example: Find the average 'sepal_length' and 'sepal_width' after cleaning
iris[['sepal_length', 'sepal_width']].mean()

sepal_length    5.871233
sepal_width     3.050000
dtype: float64