<a href="https://colab.research.google.com/github/NatashaKamami/Python-Data-Analysis/blob/main/TimeSeries_FinancialData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting Financial Data - Google Finance

### Introduction:

This time you will get data from a website.


### Step 1. Import the necessary libraries

In [ ]:
import pandas as pd
import yfinance as yf # to fetch financial data like stock prices directly from the web
from datetime import datetime

### Step 2. Create your time range (start and end variables). The start date should be 01/01/2015 and the end should today (whatever your today is)

In [ ]:
start_date = "2015-01-01"
end_date = "2024-11-08"

### Step 3. Select the Apple, Tesla, Twitter, IBM, LinkedIn stocks symbols and assign them to a variable called stocks

In [ ]:
stocks = ['AAPL', 'TSLA', 'IBM']

### Step 4. Read the data from google, assign to df and print it

In [ ]:
df = yf.download(stocks, start=start_date, end=end_date)
df.head()

[*********************100%***********************]  3 of 3 completed

Price                      Adj Close                             Close  \
Ticker                          AAPL         IBM       TSLA       AAPL
Date
2015-01-02 00:00:00+00:00  24.373960  101.451599  14.620667  27.332500
2015-01-05 00:00:00+00:00  23.687304   99.855270  14.006000  26.562500
2015-01-06 00:00:00+00:00  23.689535   97.701797  14.085333  26.565001
2015-01-07 00:00:00+00:00  24.021717   97.063240  14.063333  26.937500
2015-01-08 00:00:00+00:00  24.944687   99.172935  14.041333  27.972500

Price                                                  High              \
Ticker                            IBM       TSLA       AAPL         IBM
Date
2015-01-02 00:00:00+00:00  154.933075  14.620667  27.860001  156.128113
2015-01-05 00:00:00+00:00  152.495224  14.006000  27.162500  154.177826
2015-01-06 00:00:00+00:00  149.206497  14.085333  26.857500  152.925430
2015-01-07 00:00:00+00:00  148.231354  14.063333  27.049999  150.286804
2015-01-08 00:00:00+00:00  151.453156  14.041333  28.037500  152.045883

Price                                       Low                         \
Ticker                          TSLA       AAPL         IBM       TSLA
Date
2015-01-02 00:00:00+00:00  14.883333  26.837500  153.919693  14.217333
2015-01-05 00:00:00+00:00  14.433333  26.352501  152.189301  13.810667
2015-01-06 00:00:00+00:00  14.280000  26.157499  148.346085  13.614000
2015-01-07 00:00:00+00:00  14.318667  26.674999  147.256210  13.985333
2015-01-08 00:00:00+00:00  14.253333  27.174999  148.709366  14.000667

Price                           Open                            Volume  \
Ticker                          AAPL         IBM       TSLA       AAPL
Date
2015-01-02 00:00:00+00:00  27.847500  154.216064  14.858000  212818400
2015-01-05 00:00:00+00:00  27.072500  154.177826  14.303333  257142000
2015-01-06 00:00:00+00:00  26.635000  152.648178  14.004000  263188400
2015-01-07 00:00:00+00:00  26.799999  150.286804  14.223333  160423600
2015-01-08 00:00:00+00:00  27.307501  149.369019  14.187333  237458000

Price
Ticker                         IBM      TSLA
Date
2015-01-02 00:00:00+00:00  5779673  71466000
2015-01-05 00:00:00+00:00  5104898  80527500
2015-01-06 00:00:00+00:00  6429448  93928500
2015-01-07 00:00:00+00:00  4918083  44526000
2015-01-08 00:00:00+00:00  4431693  51637500

### Step 5.  What is the type of structure of df ?

In [ ]:

type(df)

pandas.core.frame.DataFrame

### Step 6. Print all the Items axis values
#### To learn more about the Panel structure go to [documentation](http://pandas.pydata.org/pandas-docs/stable/dsintro.html#panel)

In [ ]:
df.columns

MultiIndex([('Adj Close', 'AAPL'),
            ('Adj Close',  'IBM'),
            ('Adj Close', 'TSLA'),
            (    'Close', 'AAPL'),
            (    'Close',  'IBM'),
            (    'Close', 'TSLA'),
            (     'High', 'AAPL'),
            (     'High',  'IBM'),
            (     'High', 'TSLA'),
            (      'Low', 'AAPL'),
            (      'Low',  'IBM'),
            (      'Low', 'TSLA'),
            (     'Open', 'AAPL'),
            (     'Open',  'IBM'),
            (     'Open', 'TSLA'),
            (   'Volume', 'AAPL'),
            (   'Volume',  'IBM'),
            (   'Volume', 'TSLA')],
           names=['Price', 'Ticker'])

### Step 7. Good, now we know  the data avaiable. Create a dataFrame called vol, with the Volume values.

In [ ]:
vol = df['Volume']

### Step 8. Aggregate the data of Volume to weekly
#### Hint: Be careful to not sum data from the same week of 2015 and other years.

In [ ]:
vol_weekly = vol.resample('W').sum()
vol_weekly

Ticker                           AAPL       IBM       TSLA
Date
2015-01-04 00:00:00+00:00   212818400   5779673   71466000
2015-01-11 00:00:00+00:00  1133010000  25578884  340644000
2015-01-18 00:00:00+00:00  1216906400  24329751  461988000
2015-01-25 00:00:00+00:00   794948000  32682062  243175500
2015-02-01 00:00:00+00:00  1863370800  34442689  235803000
...                               ...       ...        ...
2024-10-13 00:00:00+00:00   164894900  18397900  416422000
2024-10-20 00:00:00+00:00   218141000  18477500  299317200
2024-10-27 00:00:00+00:00   197299900  31380700  537640400
2024-11-03 00:00:00+00:00   248222000  26467700  366289100
2024-11-10 00:00:00+00:00   169700700  12643100  420184700

[515 rows x 3 columns]

### Step 9. Find all the volume traded in the year of 2015

In [ ]:
vol_2015 = vol.loc['2015-01-01':'2015-12-31']
total_vol_2015 = vol_2015.sum()
total_vol_2015

Ticker
AAPL    52264199600
IBM      1156439400
TSLA    16323267000
dtype: int64

### BONUS: Create your own question and answer it.

In [ ]:
# Example - Calculate the average daily volume for each stock
vol.mean()

Ticker
AAPL    1.181273e+08
IBM     4.808293e+06
TSLA    1.125216e+08
dtype: float64